### PR TITLE
Add Hooktube provider

### PR DESCRIPTION
**Pull request by ffwff**
I've ported [web-mpris2's hooktube provider](https://github.com/shwsh/web-mpris2/blob/master/providers/youtube.js) for browser-mpris2.

Let me know if any bugs arrive.

### CODE REVIEW

**Comment by otommod** [comment]
This just doesn't work.  Each content script runs in each own JavaScript environment, separate from the site's.  So, the `endHook()` that's declared in our script will never be seen, let alone called, from the site.  This is different from userscripts.

**Comment by ffwff** [comment]
Ah, okay, I'll try to figure something out

**Comment by ffwff** [comment]
Alright, I believe it should work now.

**Comment by otommod** [comment]
While you could inject, I'd rather you used a `MutationObserver`.  I'd say it's easier too and doesn't require all these pesky permissions.

**Comment by otommod** [comment]
Great! Last thing, make the run_at document_start again and the MutationObserver run in a "load" event listener and we're good to go!

**Comment by otommod** [comment]
Thank you very much!

**Review by otommod — COMMENTED** [review]
I had no idea how that worked

**Pull request merged**
