### PR TITLE
Support for Chrome

### PR DESCRIPTION
**Pull request by orschiro**
@otommod I know not very elegant to duplicate for Chrome but it does the job...

Or do you have better ideas? :-)

### CODE REVIEW

**Comment by otommod** [comment]
I ended up implementing this myself.

**Comment by terencode** [comment]
I thought it was working for chrome before?

**Comment by orschiro** [comment]
> I ended up implementing this myself.

Thanks! Doing this in a loop is quite better. :-)

**Comment by otommod** [comment]
@terencode Sure the install script only considered chromium (since that's what I use personally)

**Comment by terencode** [comment]
Ah, get it, thanks ;)

**Pull request closed without merging**
