### PR TITLE
Add note chrome config file

### PR DESCRIPTION
**Pull request by orschiro**
To help Chrome users install correctly. :-)

### CODE REVIEW

**Comment by otommod** [comment]
TBH, I'd prefer if the install script autodetected this.  I think it'd be find if the necessary files were installed both for chromium and chrome.

**Comment by orschiro** [comment]
I agree. Do you know how to auto-detect it?

**Comment by otommod** [comment]
Like I said, just installing in both locations is probably fine.

**Comment by orschiro** [comment]
Let's disregard this in favour of https://github.com/otommod/browser-mpris2/pull/6.

**Pull request closed without merging**
